# Site settings
title: MacDown 3000
description: A Free Software Markdown editor for macOS
baseurl: ""
url: "https://macdown.app"

# Build settings
markdown: kramdown
theme: minima

# GitHub Pages settings
repository: schuyler/macdown3000

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
